chore: commit gp-pages via github-actions[bot]

diff --git a/.github/workflows/update-gh-pages.yml b/.github/workflows/update-gh-pages.yml
--- a/.github/workflows/update-gh-pages.yml
+++ b/.github/workflows/update-gh-pages.yml
@@ -48,10 +48,22 @@ jobs:
           name: web-page
           path: web-page/
 
-      - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: web-page
-          publish_branch: gh-pages
-          force_orphan: true
+      - name: Configure Git
+        run: |
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+
+      - name: Commit and Push changes
+        run: |
+          cd web-page
+          git add .
+          git commit -m "Automated deployment to GitHub Pages by GitHub Actions" || echo "No changes to commit" # Handle no changes
+          git push origin gh-pages --force #force solves conflict
+
+      # - name: Deploy to GitHub Pages (Alternative, if the above fails)
+      #   uses: peaceiris/actions-gh-pages@v3
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     publish_dir: web-page
+      #     publish_branch: gh-pages
+      #     force_orphan: true
